const express = require('express')
const { getUser, createUser, userLogin, deleteUser, getUserById, updateUser } = require('../controller/user')
const { addCategory, getCategory } = require('../controller/category')
const { getProducts, createProduct, deleteProduct, updateProduct, findProductById, findSingleProductById } = require('../controller/product')
const { upload } = require('../middleware/multer')
const { getCart, addCart, updateCart, removeCart } = require('../controller/cart')
const { verifyToken } = require('../middleware/jwt')
const { getOrders, createOrder, getOrdersByUser } = require('../controller/orders')
const { search, searchCategory } = require('../controller/search')
const Router = express.Router()

Router.get('/', (req,res)=>res.send("welcome to prcart"))
Router.get('/users', getUser)
Router.post("/users", createUser)
Router.delete("/users/:id", deleteUser)
Router.put("/users/", verifyToken, updateUser)
Router.post("/login", userLogin)
Router.post("/category", addCategory)
Router.get("/category", getCategory)
Router.get("/product", getProducts)
Router.post("/product", upload.single('file'), createProduct)
Router.delete("/product/:id", deleteProduct)
Router.put("/product/:id",upload.single('file') ,updateProduct)
Router.post("/productid", findProductById)
Router.get("/cart", verifyToken, getCart)
Router.post("/cart", verifyToken, addCart)
Router.put("/cart/:id", verifyToken, updateCart)
Router.delete("/cart/:id", verifyToken, removeCart)
Router.get("/orders", getOrders)
Router.post("/orders", verifyToken, createOrder)
Router.get("/ordersById", verifyToken, getOrdersByUser)
Router.get("/user", verifyToken, getUserById)
Router.post("/productById/:id", findSingleProductById)
Router.post("/search", search)
Router.post("/searchCategory",searchCategory)

module.exports = Router